version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    links:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/mydatabase
    restart: unless-stopped

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
